//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Primer
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧ.
    /// </summary>
    // *** Start programmer edit section *** (ТЧ CustomAttributes)

    // *** End programmer edit section *** (ТЧ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧE", new string[] {
            "Строка as \'Строка\'",
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'"})]
    public class ТЧ : ICSSoft.STORMNET.DataObject
    {
        
        private int fСтрока;
        
        private int fКоличество;
        
        private double fСумма;
        
        private IIS.Primer.Документ fДокумент;
        
        // *** Start programmer edit section *** (ТЧ CustomMembers)

        // *** End programmer edit section *** (ТЧ CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧ.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ.Количество Get start)

                // *** End programmer edit section *** (ТЧ.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧ.Количество Get end)

                // *** End programmer edit section *** (ТЧ.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ.Количество Set start)

                // *** End programmer edit section *** (ТЧ.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧ.Количество Set end)

                // *** End programmer edit section *** (ТЧ.Количество Set end)
            }
        }
        
        /// <summary>
        /// Строка.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ.Строка CustomAttributes)

        // *** End programmer edit section *** (ТЧ.Строка CustomAttributes)
        public virtual int Строка
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ.Строка Get start)

                // *** End programmer edit section *** (ТЧ.Строка Get start)
                int result = this.fСтрока;
                // *** Start programmer edit section *** (ТЧ.Строка Get end)

                // *** End programmer edit section *** (ТЧ.Строка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ.Строка Set start)

                // *** End programmer edit section *** (ТЧ.Строка Set start)
                this.fСтрока = value;
                // *** Start programmer edit section *** (ТЧ.Строка Set end)

                // *** End programmer edit section *** (ТЧ.Строка Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ.Сумма CustomAttributes)

        // *** End programmer edit section *** (ТЧ.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ.Сумма Get start)

                // *** End programmer edit section *** (ТЧ.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ТЧ.Сумма Get end)

                // *** End programmer edit section *** (ТЧ.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ.Сумма Set start)

                // *** End programmer edit section *** (ТЧ.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ТЧ.Сумма Set end)

                // *** End programmer edit section *** (ТЧ.Сумма Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Primer.Документ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ.Документ CustomAttributes)

        // *** End programmer edit section *** (ТЧ.Документ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Документ"})]
        public virtual IIS.Primer.Документ Документ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ.Документ Get start)

                // *** End programmer edit section *** (ТЧ.Документ Get start)
                IIS.Primer.Документ result = this.fДокумент;
                // *** Start programmer edit section *** (ТЧ.Документ Get end)

                // *** End programmer edit section *** (ТЧ.Документ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ.Документ Set start)

                // *** End programmer edit section *** (ТЧ.Документ Set start)
                this.fДокумент = value;
                // *** Start programmer edit section *** (ТЧ.Документ Set end)

                // *** End programmer edit section *** (ТЧ.Документ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧE", typeof(IIS.Primer.ТЧ));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧ.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧ CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧ CustomAttributes)
    public class DetailArrayOfТЧ : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Primer.DetailArrayOfТЧ members)

        // *** End programmer edit section *** (IIS.Primer.DetailArrayOfТЧ members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧ by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧ.
        /// </summary>
        public DetailArrayOfТЧ(IIS.Primer.Документ fДокумент) : 
                base(typeof(ТЧ), ((ICSSoft.STORMNET.DataObject)(fДокумент)))
        {
        }
        
        public IIS.Primer.ТЧ this[int index]
        {
            get
            {
                return ((IIS.Primer.ТЧ)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Primer.ТЧ dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
